### ISSUE TITLE
Home Animation

### ISSUE THREAD

**Issue by craigcoles** [mattkersley/mattkersley.github.io#1]
If you scroll down on the homepage and click the link to the article, once on that page if you click the back button, you land back on the homepage but at the bottom of the page (browsers retains scroll location), and this is blank due to the animation firing at the top of the page.

Hope this helps man :+1:

**Comment by mattkersley** [comment]
Hah, yeah.
I did consider doing something with cookies/localstorage to negate this exact issue - then promptly forgot. Thanks for the reminder.
